<a href="https://colab.research.google.com/github/Ds2023/Pandas_Numpy_Prac/blob/main/Numpy_Cont.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing the necessary library.**

In [34]:
import numpy as np

**Sorting of arrays**

 Sorting refers to arranging the elements of an array or a list in a particular order.

In [35]:
x = np.array([2, 1, 4, 3, 5])

In [36]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [37]:
x.sort()

In [38]:
print(x)

[1 2 3 4 5]


In [39]:
# Descending order

x[::-1]

array([5, 4, 3, 2, 1])

**Arg Sort**

**Returns the indices of the sorted elements.**

In [40]:
x = np.array([2, 1, 4, 3, 5])

In [41]:
x

array([2, 1, 4, 3, 5])

In [43]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [44]:
i = np.argsort(x)
print(i)

[1 0 3 2 4]


**Sorting along rows or columns**

In [46]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [47]:
# Columnwise

np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [48]:
# Row-wise

np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

**Partitioning**

**We want to find the k smallest values in the array.**

In [49]:
arr = np.array([3, 7, 9, 1, 5, 2, 8, 4, 6])

In [ ]:
# Three smallest

np.partition(arr, 3)

array([1, 2, 3, 4, 5, 7, 8, 9, 6])

In [52]:
np.partition(arr,4)

array([2, 3, 4, 1, 5, 7, 8, 9, 6])

**Partitioning along a specific axis**

In [53]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
X

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [57]:
# Row-wise

np.partition(X, 4, axis=1)

array([[6, 6, 3, 4, 7, 9],
       [3, 2, 6, 4, 7, 7],
       [1, 5, 2, 4, 7, 7],
       [0, 4, 1, 5, 5, 9]])

In [58]:
# Column wise

np.partition(X, 2, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

**Basic Math Operations**

In [68]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [69]:
list1

array([0.47982805, 0.28735321, 0.34838592, 0.67459678, 0.93565589,
       0.81631383, 0.35320878, 0.40002436, 0.33972788, 0.20555665])

In [70]:
list2

array([0.27409953, 0.87474718, 0.54992336, 0.43873909, 0.62833246,
       0.89846613, 0.94684557, 0.91651458, 0.37377386, 0.80311524])

In [71]:
add = np.add(list1, list2)
add

array([0.75392758, 1.16210039, 0.89830928, 1.11333587, 1.56398835,
       1.71477996, 1.30005435, 1.31653894, 0.71350174, 1.00867189])

In [72]:
sub = np.subtract(list1, list2)
sub

array([ 0.20572852, -0.58739397, -0.20153743,  0.23585769,  0.30732343,
       -0.08215229, -0.59363679, -0.51649022, -0.03404597, -0.59755858])

In [73]:
div = np.divide(list1, list2)
div

array([1.75056138, 0.32849858, 0.63351723, 1.53758074, 1.48910959,
       0.90856384, 0.37303737, 0.43646263, 0.90891291, 0.25594914])

In [74]:
mult = np.multiply(list1, list2)
mult

array([0.13152064, 0.25136141, 0.19158556, 0.29597198, 0.58790296,
       0.73343033, 0.33443417, 0.36662816, 0.1269814 , 0.16508568])

In [75]:
dot = np.dot(list1, list2)
dot

3.1849022836273413

In [76]:
sqrt = np.sqrt(25)
sqrt

5.0

In [77]:
ab = np.abs(-2)
ab

2

In [79]:
power = np.power(2,3)
power

8

In [80]:
log = np.log(25)
log

3.2188758248682006

In [82]:
np.log10(20)

1.3010299956639813

In [83]:
exp = np.exp([2,3])
exp

array([ 7.3890561 , 20.08553692])

In [84]:
list1

array([0.47982805, 0.28735321, 0.34838592, 0.67459678, 0.93565589,
       0.81631383, 0.35320878, 0.40002436, 0.33972788, 0.20555665])

In [85]:
mins = np.min(list1)
mins

0.20555665356835162

In [86]:
maxs = np.max(list1)
maxs

0.9356558898112015

**Accessing specific elements**

In [93]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [90]:
a.nbytes

112

In [91]:
# Get a specific element [r, c]
a[1, 5]

13

In [92]:
a[0,2]

3

In [94]:
# Extract 18
a[2,3]

18

In [97]:
# Get a specific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [98]:
# Get a specific column
a[:, 2]

array([ 3, 10, 17])

In [99]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [102]:
# 1,3,5,7
a[0,0:-3:2]

array([1, 3])

In [100]:
# 8,10,12,14
a[1,0::2]

array([ 8, 10, 12, 14])

In [95]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [104]:
# Getting a little more fancy [startindex:endindex:stepsize]
# 16,19
a[2,1:-2:3]

array([16, 19])

In [105]:
a[2,1::3]

array([16, 19])

In [106]:
a[0, 1::2]

array([2, 4, 6])