# **Introduction to Numpy**

**What is NumPy?**

NumPy (Numerical Python) is a  powerful library in Python for numerical and mathematical operations.

**Why Numpy?**

It allows for:
- Numerical Calculations
- Multidimensional array storage
- Matrices storage

Key features of the library include;
- Arrays
- Mathematical functions
- Random Number Generation
- Broadcasting etc







# **Installation and Importing**

In [ ]:
## Installation of numpy

## pip install numpy

In [ ]:
pip install numpy

In [ ]:
# Importing Numpy

import numpy as np

In [ ]:
np?

# **Numpy Arrays**

**What is a NumPy Array?**

**Definition**: A NumPy array is a multidimensional, homogeneous data structure that allows you to store and manipulate large datasets efficiently.

**Homogeneous Data**: Unlike Python lists, NumPy arrays contain elements of the same data type. This homogeneity allows for optimized memory storage and efficient element-wise operations.

**Multidimensional**: NumPy arrays can have multiple dimensions (1D, 2D, 3D, etc.), making them suitable for representing matrices, vectors, and higher-dimensional data.

**Key Features:**

**Efficiency:**

NumPy arrays are implemented in C and provide efficient storage and operations on large datasets, making them faster than regular Python lists.

**Element-wise Operations:**

NumPy enables you to perform operations on entire arrays without the need for explicit looping. This is known as vectorization, a key feature that enhances code readability and performance.

**Broadcasting:**

NumPy supports broadcasting, allowing for operations between arrays of different shapes and sizes. This simplifies code and makes it more flexible.

**Indexing and Slicing:**

Similar to Python lists, NumPy arrays support indexing and slicing, making it easy to extract specific elements or subarrays.

# **Numpy Data Types:**

**Integer Types:**

np.int8, np.int16, np.int32, np.int64: Signed integer types with 8, 16, 32, or 64 bits.
np.uint8, np.uint16, np.uint32, np.uint64: Unsigned integer types with 8, 16, 32, or 64 bits.

**Floating-Point Types:**

np.float16, np.float32, np.float64: Floating-point types with 16, 32, or 64 bits.
np.complex64, np.complex128: Complex number types with 64 or 128 bits.

**Other Numeric Types:**

np.bool: Boolean type.
np.object: Object type, which can hold any Python object.
np.str_, np.unicode_: String types for ASCII and Unicode strings.

**Special Types:**

np.void: Void type, used for custom data types.

**Generic Types:**

np.number: Generic numeric type (superclass of all numeric types).
np.integer: Generic integer type (superclass of all integer types).
np.floating: Generic floating-point type (superclass of all floating-point types).

# **Creating Arrays**

**From a python list**

In [ ]:
python_list = [1, 2, 3, 4, 5]
python_list

[1, 2, 3, 4, 5]

In [ ]:
numpy_array = np.array(python_list)
print(numpy_array)

[1 2 3 4 5]


In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
print(f"Python List : {type(python_list)}")
print(f"Numpy Array : {type(numpy_array)}")

Python List : <class 'list'>
Numpy Array : <class 'numpy.ndarray'>


In [ ]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

**Using 'arange'**

In [ ]:
# Create an array with values from 0 to x-1

arr = np.arange(15)
print(arr)
print(type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


**Using 'zeros' and 'ones'**

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
# Create an array with all zeros of desired shape

zeros_array = np.zeros((3, 4))

# Create an array of ones with shape (2, 3)
ones_array = np.ones((2, 3))

print("Zeros Array:")
print(zeros_array)
print("\n")
print("Ones Array:")
print(ones_array)

Zeros Array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]


**Using 'linspace'**

In [ ]:
# Creates an array of x values between a,b -- np.linspace(a,b,x)

arr = np.linspace(2,8,4)
print(arr)

[2. 4. 6. 8.]


**Using 'full'**

In [ ]:
# numpy.full(shape, fill_value, dtype=None, order='C')

arr = np.full((2,3),3)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]]


In [ ]:
# Generate a random float between 0 and 1 --takes size as input

arr = np.random.random((4,3))
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[0.00837054 0.45954597 0.28011908]
 [0.54718773 0.37958565 0.43817476]
 [0.95961646 0.88141166 0.77335607]
 [0.79409388 0.6156478  0.58953403]]


In [ ]:
# random.randint(low, high=None, size=None, dtype=int)
# Return random integers from low (inclusive) to high (exclusive).

arr1 = np.random.randint(40,50,5,dtype='int')
print(type(arr1))
print(arr1)
print("\n")
arr2 = np.random.randint(40,50,(2,2))
print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
[46 46 48 46 46]


<class 'numpy.ndarray'>
[[42 43]
 [47 40]]


In [ ]:
# random.normal(loc=0.0, scale=1.0, size=None)
# Draw random samples from a normal (Gaussian) distribution.

arr = np.random.normal(3, 2.5, size=(2, 4))
print(type(arr))
print(arr)
print("\n")
arr2 = np.random.normal(3)
print(type(arr2))
print(arr2)

<class 'numpy.ndarray'>
[[2.64084176 6.92419705 5.67606603 6.5546035 ]
 [5.4718535  5.91938266 4.17187001 1.59782606]]


<class 'float'>
1.5936460932291023


**Using 'eye'**

In [ ]:
# Create a 3x3 identity matrix (all elements of the main diagonal are equal to 1, and all other elements are equal to 0)
identity_matrix = np.eye(3)

print(type(identity_matrix))
print(identity_matrix)

<class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Creating a custom array** + **Numpy Attributes**

In [ ]:
np.array([1,2,5])

array([1, 2, 5])

In [ ]:
mat = np.array([[1,2,3],[7,8,9],[10,11,12]],dtype='int')
print(mat)

[[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Printing array dimensions (axes)
print("No. of dimensions: ", mat.ndim)
print("\n")
# Printing shape of array
print("Shape of array: ", mat.shape)
print("\n")
# Printing size (total number of elements) of array
print("Size of array: ", mat.size)
print("\n")
# Printing type of elements in array
print("Array stores elements of type: ", mat.dtype)

No. of dimensions:  2


Shape of array:  (3, 3)


Size of array:  9


Array stores elements of type:  int64


In [ ]:
# 3 dimensional array

nested_lists = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

nested_lists

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
nested_lists.ndim

3

In [ ]:
nested_lists.shape

(3, 3, 3)

In [ ]:
nested_lists.size

27

In [ ]:
import numpy as np

# Integer types
int_arr = np.array([1, 2, 3], dtype=np.int32)
print(type(int_arr))
print(int_arr)
print(int_arr.dtype)
print("\n")
# Floating-point types
float_arr = np.array([1.0, 2.5, 3.7], dtype=np.float64)
print(type(float_arr))
print(float_arr)
print(float_arr.dtype)
print("\n")
# Boolean type
bool_arr = np.array([True, False, True], dtype=bool)
print(type(bool_arr))
print(bool_arr)
print(bool_arr.dtype)
print("\n")
# Complex number type
complex_arr = np.array([1 + 2j, 3 - 4j], dtype=np.complex128)
print(type(complex_arr))
print(complex_arr)
print(complex_arr.dtype)
print("\n")
# String type
str_arr = np.array(['hello', 'world'], dtype=np.str_)
print(type(str_arr))
print(str_arr)
print(str_arr.dtype)
print("\n")
# Object type
object_arr = np.array([1, 'two', 3.0], dtype=object)
print(type(object_arr))
print(object_arr)
print(object_arr.dtype)

<class 'numpy.ndarray'>
[1 2 3]
int32


<class 'numpy.ndarray'>
[1.  2.5 3.7]
float64


<class 'numpy.ndarray'>
[ True False  True]
bool


<class 'numpy.ndarray'>
[1.+2.j 3.-4.j]
complex128


<class 'numpy.ndarray'>
['hello' 'world']
<U5


<class 'numpy.ndarray'>
[1 'two' 3.0]
object


# **Basic Numpy Operations**

**Reshaping Arrays**

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Shape : {arr.shape}")
print(arr)
print("\n")
arr2 = arr.reshape(6,1)
print(f"Arr 2 Shape : {arr2.shape}")
print(arr2)

Shape : (2, 3)
[[1 2 3]
 [4 5 6]]


Arr 2 Shape : (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# Concatenate along axis 0 (rows)
concatenated_array = np.concatenate((arr1, arr2))

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Concatenated Array:", concatenated_array)


Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenated Array: [1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2,3])

arr2 = np.array([4, 5, 6])

# Concatenate along axis 0 (rows)
concatenated_array = np.concatenate((arr1, arr2),axis=1)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Concatenated Array:", concatenated_array)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
axis = 0 rowwise
axis = 1 columnwise

In [ ]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Concatenate along columns
result = np.concatenate((array1, array2), axis=1)
print(result)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


**Operations on a single array**

In [ ]:
num = [1,2,3,4]
add = 1
for i in num:
  sum = i + add
  print(sum)

2
3
4
5


In [ ]:
num + add

TypeError: can only concatenate list (not "int") to list

In [ ]:
a = np.array([1, 2, 5, 3])

# add 1 to every element
print ("Adding 1 to every element:", a+1)

# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print ("Multiplying each element by 10:", a*10)

# square each element
print ("Squaring each element:", a**2)


Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]


In [ ]:
a = [1,2,5,3]
print(type(a))
print(a + 1)

<class 'list'>


TypeError: can only concatenate list (not "int") to list

In [ ]:
import time

In [ ]:
# Create a large dataset
size = 10**8
python_list = list(range(size))
numpy_array = np.array(python_list)

# Sum using Python list
start_time = time.time()
python_list_sum = sum(python_list)
end_time = time.time()
python_list_time = end_time - start_time

# Sum using NumPy array
start_time = time.time()
numpy_array_sum = np.sum(numpy_array)
end_time = time.time()
numpy_array_time = end_time - start_time

print(f"Sum using Python List: {python_list_sum}, Time: {python_list_time:.6f} seconds")
print(f"Sum using NumPy Array: {numpy_array_sum}, Time: {numpy_array_time:.6f} seconds")

Sum using Python List: 4999999950000000, Time: 0.945462 seconds
Sum using NumPy Array: 4999999950000000, Time: 0.121986 seconds


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
sum_elements = np.sum(arr)

# Mean of all elements
mean_value = np.mean(arr)

# Maximum element
max_value = np.max(arr)

# Minimum element
min_value = np.min(arr)


print("Original Array:", arr)
print("Sum:", sum_elements)
print("Mean:", mean_value)
print("Max:", max_value)
print("Min", min_value)

Original Array: [1 2 3 4 5]
Sum: 15
Mean: 3.0
Max: 5
Min 1


**Vectorization (Arrays vs Lists)**

In [ ]:
import numpy as np

In [ ]:
# Creating two Python lists
a_list = [1, 2, 3, 4, 5]
b_list = [6, 7, 8, 9, 10]

# Element-wise addition using a loop
result_list = []
for i in range(len(a_list)):
    result_list.append(a_list[i] + b_list[i])

print(result_list)  # Output: [7, 9, 11, 13, 15]

[7, 9, 11, 13, 15]


In [ ]:
# Creating two NumPy arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Element-wise addition using vectorization
result = a + b

print(result)  # Output: [ 7  9 11 13 15]


[ 7  9 11 13 15]


**Broadcasting**

In [ ]:
# Creating a 2x3 array
a = np.array([[1, 2, 3],
              [4, 5, 6]])

# Creating a 1x3 array
b = np.array([10, 20, 30])

# Performing broadcasting addition
result = a + b
print(a)
print()
print(b)
print(result)

[[1 2 3]
 [4 5 6]]

[10 20 30]
[[11 22 33]
 [14 25 36]]


In [ ]:
# Creating a 3x3 array
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Creating a 1x3 array
b = np.array([10, 20, 30])

# Performing broadcasting subtraction
result = a - b

print(result)

[[ -9 -18 -27]
 [ -6 -15 -24]
 [ -3 -12 -21]]
